name: chatapp
description: A new Flutter chatapp.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  shared_preferences: ^2.0.15
  modal_progress_hud: ^0.1.3
  fluttertoast: ^8.0.9
  email_auth: ^1.0.0
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  file_picker: ^4.6.1
  firebase_storage: ^10.3.1
  mysql1: ^0.20.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DS
      fonts:
        - asset: fonts/static/DancingScript-Bold.ttf
